[package]
name = "multiplayer"
edition = "2021"
version = { workspace = true }
publish = false

[dependencies]
rand = "0.8.5"
ambient_api = { path = "../../api" }

[lib]
crate-type = ["cdylib"]
required-features = []
